# Generated by Django 2.2.6 on 2019-10-30 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmdb', '0024_allow_null_registration_doc_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='short',
            field=models.CharField(default='', max_length=127),
            preserve_default=False,
        ),
    ]
